### ISSUE TITLE
Error change

### ISSUE THREAD

**Issue by tteeee** [h1karo/ShareControl#4]
Could not pass event PlayerGameModeChangeEvent to ShareControl v2.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:753) [server.jar:git-Spigot-db6de12-18fbb24]
        at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:66) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:146) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:438) [EssentialsX-2.0.1.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:348) [EssentialsX-2.0.1.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.NullPointerException
        at com.net.h1karo.sharecontrol.listeners.multiinventories.PlayerGameModeChangeListener.UniversalCaching(PlayerGameModeChangeListener.java:142) ~[?:?]
        at com.net.h1karo.sharecontrol.listeners.multiinventories.PlayerGameModeChangeListener.caching(PlayerGameModeChangeListener.java:106) ~[?:?]
        at com.net.h1karo.sharecontrol.listeners.multiinventories.PlayerGameModeChangeListener.ChangeGameMode(PlayerGameModeChangeListener.java:62) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor592.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72-internal]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]

**Comment by h1karo** [comment]
Fixed in version 2.5.1.
