### ISSUE TITLE
sqlite / mysql. Create db.

### ISSUE THREAD

**Issue by tteeee** [h1karo/ShareControl#5]
```
[20:35:43 INFO]: [ShareControl] Database have been background saved!
[20:35:43 INFO]: Error in SQL query: [SQLITE_ERROR] SQL error or missing database (no such column: world)
[20:35:43 WARN]: Exception in thread "Craft Scheduler Thread - 27512"
[20:35:43 WARN]: org.apache.commons.lang.UnhandledException: Plugin ShareControl v2.5.2 generated an exception while executing task 2148223
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.net.h1karo.sharecontrol.database.MySQL.SQLUpdate(MySQL.java:218)
        at com.net.h1karo.sharecontrol.database.Database.SQLSave(Database.java:403)
        at com.net.h1karo.sharecontrol.database.Database.saveDatabase(Database.java:57)
        at com.net.h1karo.sharecontrol.database.Database$1.run(Database.java:73)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

```

**Comment by h1karo** [comment]
If you've used up to this version prior to version 2.4 remove the blocks.db file located in the directory plugins/ShareControl/data. Note that this will remove all the blocks list from the database. The database does not support the new version of the database version 2.3.13 and below.
